services:
  postgres:
    image: postgres:latest
    container_name: postgres_spark
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "25432:5432"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
